#Language:
reload-message: "&a[Ethria-Light] Konfiguration neu geladen."
nopermission: "&a[Ethria-Light] Du hast keine Berechtigung für diesen Befehl."

# Modell-ID: Lightlevel

glowing_items:
  4304307: 15
  4304308: 15
  4304309: 15
  4304310: 15
  4304311: 15
  4304312: 15
  4304313: 15
