# Modell-ID: Lightlevel
glowing_items:
  4304307: 15
  4304308: 15
  4304309: 15
  4304310: 15
  4304311: 15
  4304312: 15
  4304313: 15

# message
reload-message: "&a[Ethria-Light] Konfiguration neu geladen."
nopermission: "&c[Ethria-Light] Du hast keine Berechtigung für diesen Befehl."

#Commandalias
command-aliases:
  - clreload
  - lightreload