name: CustomLight
main: Bloody_Mind.CustomLight
version: 1.1
api-version: 1.20
depend: [ItemsAdder]
commands:
  clreload:
    description: Reloadet die CustomLight-Konfiguration
    usage: /<command>
    permission: customlight.reload
