name: CustomLight
main: bloody_mind.customLight.CustomLight
version: 1.1
api-version: 1.20
depend: [ItemsAdder]
commands:
  customlight:
    description: Reloadet die CustomLight-Konfiguration
    usage: /<command>
    permission: customlight.reload
