name: CustomLight
main: bloody_mind.customLight.CustomLight
version: 1.3
api-version: 1.19
author: Leahcimkrob
commands:
  customlight:
    description: Main command for the CustomLight plugin
    usage: /<command> [reload|help]
    aliases: [] # Is set dynamically from the config
permissions:
  customlight.use:
    description: Allows using the CustomLight main command
    default: true
  customlight.reload:
    description: Allows reloading the configuration
    default: op