name: GlowingHalo
main: Bloody_Mind.package.CustomLight.CustomLight
version: 1.1
api-version: 1.20
depend: [ItemsAdder]
commands:
  clreload:
    description: Reloadet die GlowingHalo-Konfiguration
    usage: /<command>
